	
service: flask-rest
 
provider:
 name: aws
 stage: dev
 runtime: python3.8
 region: us-east-1
 memorySize: 128
plugins:
  - serverless-wsgi
  - serverless-python-requirements
	
custom:
  pythonRequirements:
    fileName: requirements.txt
  wsgi:
    app: app.app
    pythonBin: python3
    packRequirements: false
functions:
  app:
    handler: wsgi.handler
    events:
     - http: ANY /
     - http: 'ANY {proxy+}'